language: go

addons:
  apt:
    packages:
      - python-pygments

install:
  - go get github.com/gohugoio/hugo
  - rm -rf public

script:
  - hugo

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: public
  target-branch: master
  on:
    branch: hugo
