---
baseURL: "https://zoresvit.github.io"
languageCode: "en-us"
title: "Cryptoblog by Ruslan Kiyanchuk"
theme: "specialized"

pygmentsStyle: github

params:
  author: Ruslan Kiyanchuk
  description: "Cryptoblog by Ruslan Kiyanchuk"
