---
baseURL: "https://kiyanchuk.com"
languageCode: "en-us"
title: "Cryptography & Software Engineering"
theme: "specialized"

pygmentsStyle: github

params:
  author: Ruslan Kiyanchuk
  description: "Cryptography & Software Engineering"
