baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Ruslan Kiyanchuk'
theme = 'paper-tex'

languagecode = "en"
defaultcontentlanguage = "en"

[params]
  author = "Ruslan Kiyanchuk"
  info = "Full Stack DevOps and Magician"
  description = "John Doe's personal website"
  keywords = "blog,developer,personal"
  colorScheme = "auto"
  hidecolorschemetoggle = false

[markup.highlight]
style = "github"

 

[menu]
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    url = "/tags/"