baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Ruslan Kiyanchuk'
theme = 'paper-tex'

languagecode = "en"
defaultcontentlanguage = "en"

[params]
  author = "Ruslan Kiyanchuk"
  info = "Full Stack DevOps and Magician"
  description = "John Doe's personal website"
  keywords = "blog,developer,personal"
  colorScheme = "auto"
  hidecolorschemetoggle = false

[markup.highlight]
style = "github"